server.port=8080
# Usamos el valor de Railway, y si no existe, el que pusiste (que es correcto según tu captura)
nyt.api.key=${NYT_API_KEY:EYB5r3OP0pEbuakUYPwc5ixlrSqKMBj3Nco0KEVp8XJGfewq}
nyt.base.url=https://api.nytimes.com/svc/books/v3
management.endpoints.web.exposure.include=health